partial script work for jarmodulehacking

diff --git a/virtdata-userlibs/mkmods b/virtdata-userlibs/mkmods
--- a/virtdata-userlibs/mkmods
+++ b/virtdata-userlibs/mkmods
@@ -1,46 +1,63 @@
 #!/bin/bash
+
+export JAVA_HOME=${JAVA_HOME:?JAVA_HOME must be set}
+export PATH=$JAVA_HOME/bin:$PATH
+
 rm -f mkmods.log
-exec 3<>mkmods.log
+exec 2>mkmods.log
+set -x
 # to redirect anything to this log, just add 1>&3 to the end of the command
 
 export TARGETDIR=${TARGETDIR:-target}
-export DEPSSUBDIR=${DEPSSUBDIR:-dependencies}
-export JMODSUBDIR=${JMODSUBDIR:-jmods}
-
 pushd ${TARGETDIR}
 
-#for file in $(find $DEPSDIR -type f -name '*.jar')
-for file in $(find $DEPSDIR -type f -name '*assert*.jar')
+export DEPSIMGDIR=${DEPSIMGDIR:-deps-image}
+export JMODSUBDIR=${JMODSUBDIR:-jmods}
+
+printf "DEPSIMGDIR=${DEPSIMGDIR} JMODSUBDIR=${JMODSUBDIR} MODSDIR=${MODSDIR}\n"
+
+
+#for file in $(find $DEPSIMGDIR -type f -name '*.jar')
+if [ ! -d "${DEPSIMGDIR}" ]
+then
+ printf "deps dir 'DEPSIMGDIR' does not exist: %s\n" ${DEPSIMGDIR};
+ exit 2
+fi
+
+printf "pwd:%s\n" $(pwd)
+
+for file in $(find $DEPSIMGDIR -type f -name '*number-to-words*.jar')
 do
  jarname=$(basename $file)
  modname=${jarname%%-[0-9.]*.jar}
  modname=${modname//-/.}
+
  printf "file:%s \n jarname:%s\n modname:%s\n" "${file}" "${jarname}" "${modname}"
- jdeps --multi-release 12 --module-path *.jar:dependencies --generate-module-info ${JMODSUBDIR} $file
- modulefile=${JMODSUBDIR}/${modname}/module-info.java
- if [ -f "${modulefile}" ]
+
+ if unzip -l "${modulefile}" | grep 'module-info'
  then
-  printf " PRESENT\n"
+  printf "FOUND MODULE-INFO...\n"
  else
-  printf " MISSING\n"
+  printf "NOT A MODULE\n"
+   jdeps --multi-release 12 --module-path *.jar:${TARGETDIR}/${DEPSIMGDIR} --generate-module-info ${JMODSUBDIR} $file
+   modulefile=${JMODSUBDIR}/${modname}/module-info.java
+   if [ -f "${modulefile}" ]
+   then
+    printf " PRESENT\n"
+    pushd ${JMODSUBDIR}/${modname}
+     printf "PWD %s\n"  $(pwd)
+     unzip ../../${file}
+     javac module-info.java
+#     jar uf ${modulefile} -C $ROOT_DIR/classes module-info.class
+    popd
+   else
+    printf " MISSING\n"
+   fi
  fi
 
 done
-#!/bin/bash
+exit 0
 
-if [ ! -d "target/dependencies" ]
-then
- printf "target/dependencies directory does not exist. Exiting!\n"
- exit 2
-fi
-
-cd target
-mkdir -p jmods
-export MAINDIR=`pwd`
-
-for file in dependencies/*.jar
-do
- printf "examining file '%s' ...\n" ${file}
  if unzip -l $file | grep 'module-info'
  then
   printf "FOUND MODULE-INFO...\n"
